# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "Kami"
license = "MIT"
licenselink = "https://github.com/Akagi201/kami/blob/master/LICENSE.md"
description = "Kami is a theme designed for blogging."
homepage = "https://github.com/Akagi201/kami"
tags = ["blog",]
features = ["blog",]
min_version = 0.15

[author]
  name = "Akagi201"
  homepage = "http://akagi201.org"

# If porting an existing theme
[original]
  name = "mdo"
  homepage = "http://hyde.getpoole.com/"
  repo = "https://www.github.com/mdo/hyde"
